### PR TITLE
[WIP] ♻️ 🚧 🔧 Windows/Mac script and clean-upgrade repo directories

### PR DESCRIPTION
**Pull request by MasterCruelty**
* Added three folder: <b>Linux, Windows </b> and <b> Mac</b>
* Added a Powershell script which does the update of Windows systems.

@archetipico if it looks good to you, I'll code and add the Mac script in the right folder.

### CODE REVIEW

**Review by MasterCruelty — COMMENTED** [review]
Just moved these files, no changes.

**Review by MasterCruelty — COMMENTED** [review]
Created privileges.ps1 to check and get admin privileges when run powershell.
Created winUpdate.ps1 which does the entire update of Windows system.

**Comment by MasterCruelty** [comment]
@archetipico check it out when you have free time

**Comment by MasterCruelty** [comment]
Next commits, I'll create a first Python source for the functioning of install,uninstall and update bash source files

**Comment by MasterCruelty** [comment]
Gonna add #109 #107 here then

**Review by archetipico — APPROVED** [review]

**Pull request merged**
